### ISSUE TITLE
Super cool - few questions

### ISSUE THREAD

**Issue by ghost** [notwaldorf/cat-push-notifications#7]
i want to try this out for a Polymer project that is Web, Desktop, Android and IOS based.
So, i am using Cordova to wrap the web app as per normal.

Can you give me any tips regarding this, and if i need to use the Cordova Notifications to make it work on Mobile.

**Comment by notwaldorf** [comment]
This demo only works on Chrome (desktop and Android mobile, not iOS mobile), because it only uses GCM. If you wanted to make it work automagically on all devices, then you need your server to know how to speak to the other messaging servers.

For example, for APN (the Apple push notifications server) this might be a good start: https://developer.apple.com/library/mac/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/Introduction/Introduction.html. 

Unfortunately I don't know anything about Cordova and if that could help. Sorry! :(
